name: carymessenger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  abilia_sync:
    path: ../packages/abilia_sync
  auth:
    path: ../packages/auth
  bloc: ^8.0.2
  calendar:
    path: ../packages/calendar
  calendar_events:
    path: ../packages/calendar_events
  collection: ^1.17.0
  equatable: ^2.0.3
  file_storage:
    path: ../packages/file_storage
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  generics:
    path: ../packages/generics
  get_it: ^7.2.0
  intl: ^0.18.0
  logging: ^1.1.0
  lokalise_flutter_sdk: ^1.1.1
  meta: ^1.9.1
  package_info_plus: ^4.1.0
  path_provider: ^2.0.5
  permission_handler: ^10.2.0
  repository_base:
    path: ../packages/repository/repository_base
  rxdart: ^0.27.1
  seagull_analytics:
    path: ../packages/seagull_analytics
  seagull_clock:
    path: ../packages/seagull_clock
  seagull_logging:
    path: ../packages/seagull_logging
  shared_preferences: ^2.0.8
  sortables:
    path: ../packages/sortables
  sqflite: ^2.2.5
  sqflite_common_ffi: ^2.2.5
  timezone: ^0.9.0
  transparent_image: ^2.0.0
  user_files:
    path: ../packages/user_files
  utils:
    path: ../packages/utils

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  mocktail: ^1.0.0
  seagull_fakes:
    path: ../packages/seagull_fakes
  seagull_lints:
    path: ../packages/seagull_lints

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
