name: repository_base

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.3
  http: ^0.13.5
  path: ^1.8.1
  shared_preferences: ^2.0.8
  sqflite: ^2.2.0
  sqflite_common_ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  seagull_fakes:
    path: ../../seagull_fakes
  seagull_lints:
    path: ../../seagull_lints
