name: repository_base

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  collection: any
  equatable: any
  http: any
  logging: any
  meta: any
  path: any
  shared_preferences: any
  sqflite: any
  sqflite_common_ffi: any
  synchronized: any
  utils:
    path: ../../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  seagull_fakes:
    path: ../../seagull_fakes
  seagull_lints:
    path: ../../seagull_lints
