name: seagull
description: The seagull app.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.5
  flutter_bloc: ^3.2.0
  meta: ^1.1.7
  equatable: ^1.0.0
  http: ^0.12.0+2
  uuid: ^2.0.2
  firebase_messaging:
    git:
      url: git://github.com/abilia/flutterfire.git
      ref: ios-background-support
      path: packages/firebase_messaging/
  sqflite: ^1.1.7+3
  get_it: ^3.0.3
  shared_preferences: ^0.5.4+8
  path_provider: ^1.4.5
  package_info: ^0.4.0+13
  flutter_local_notifications:
    git:
      url: git://github.com/abilia/flutter_local_notifications.git
      ref: dev
      path: flutter_local_notifications/
  transparent_image: ^1.0.0
  rxdart: ^0.23.0
  dotted_border: ^1.0.4
  synchronized: ^2.2.0
  image_picker: ^0.6.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  mockito: ^4.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
