name: seagull
description: The seagull app.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.2.5
  flutter_bloc: ^2.0.0
  meta: ^1.1.7
  equatable: ^1.0.0
  http: ^0.12.0+2
  uuid: ^2.0.2
  flutter_secure_storage: ^3.3.1+1
  firebase_messaging: ^6.0.1
  sqflite: ^1.1.7+3
  sqflite_migration: ^0.1.2
  get_it: ^3.0.3
  shared_preferences: ^0.5.4+8
  path_provider: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  mockito: ^4.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
