name: seagull
description: The seagull app.
version: 1.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent_plus: ^1.0.1
  audioplayers: ^0.18.3
  collection: ^1.15.0-nullsafety.4
  devicelocale: ^0.4.1
  dotted_border: ^2.0.0
  dotted_line: ^3.0.0
  equatable: ^2.0.0
  exif: ^2.0.0
  firebase_analytics: ^8.0.2
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.2
  firebase_messaging: ^9.1.3
  # flutter_appcenter_bundle: ^3.3.1+2 # Not working at the moment.
  flutter_archive: ^3.0.0
  flutter_bloc: ^7.0.0
  flutter_local_notifications:
    git:
      url: git://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v6.0.0-fork-1.10
      path: flutter_local_notifications/
  flutter_native_timezone: ^1.0.10
  flutter_ringtone_player: ^3.0.0
  flutter_tts: ^3.0.0
  get_it: ^6.1.1
  google_fonts: ^2.0.0
  http: ^0.13.2
  image_picker: ^0.7.4
  logging: ^1.0.1
  meta: ^1.1.8
  mime: ^1.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  photo_view: ^0.11.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  transparent_image: ^2.0.0
  uuid: ^3.0.4
  webview_flutter: ^2.0.4

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.0.1
  file: ^6.0.0
  flutter_launcher_icons: ^0.9.0
  mockito: ^5.0.3
  sqflite_common_ffi: ^2.0.0

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
