name: seagull
description: The seagull app.
version: 4.0.0
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  acapela_tts:
    git:
      url: https://github.com/abilia/acapela_tts.git
      ref: v1.1.3
  android_intent_plus: ^3.0.1
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0-nullsafety.0
  battery_plus: ^2.0.1
  bloc_concurrency: ^0.2.0
  collection: ^1.15.0
  connectivity_plus: ^2.1.0
  devicelocale: ^0.5.0
  dotted_border: ^2.0.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  firebase_analytics: ^9.1.2
  firebase_core: ^1.8.0
  firebase_crashlytics: ^2.2.4
  firebase_messaging: ^11.1.0
  flutter_archive: ^4.0.1
  flutter_bloc: ^8.0.1
  flutter_local_notifications:
    git:
      url: https://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v9.5.3+1-fork-2.5
      path: flutter_local_notifications/
  flutter_native_timezone: ^2.0.0
  flutter_ringtone_player: ^3.1.0
  matrix4_transform: ^2.0.1
  system_settings_editor:
    git:
      url: https://github.com/abilia/system_settings_editor.git
      ref: v1.3.3
  flutter_tts: ^3.2.2
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  image_picker: ^0.8.4
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.1
  package_info: ^2.0.2
  path_provider: ^2.0.5
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  record: ^3.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  transparent_image: ^2.0.0
  uuid: ^3.0.5
  wakelock: ^0.6.1
  webview_flutter: ^3.0.1
  youtube_player_flutter:
    git:
      url: https://github.com/SlowDeepCoder/youtube_player_flutter
      ref: master # branch name

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.4
  bloc_test: ^9.0.3
  file: ^6.1.0
  flutter_launcher_icons: ^0.9.1
  flutter_lints: ^1.0.4
  mocktail_image_network: ^0.3.1
  sqflite_common_ffi: ^2.0.0+1

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
