name: seagull
description: The seagull app.
version: 1.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent_plus: ^1.0.2
  audioplayers: ^0.19.1
  auto_size_text: ^2.1.0
  collection: ^1.15.0-nullsafety.4
  devicelocale: ^0.4.2
  dotted_border: ^2.0.0
  dotted_line: ^3.0.0
  equatable: ^2.0.3
  exif: ^3.0.0
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  flutter_archive: ^4.0.1
  flutter_bloc: ^7.1.0
  flutter_local_notifications:
    git:
      url: git://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v6.0.0-fork-1.10
      path: flutter_local_notifications/
  flutter_native_timezone: ^2.0.0
  flutter_ringtone_player: ^3.0.0
  flutter_tts: ^3.2.2
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  image_picker: ^0.8.2
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^8.1.4
  photo_view: ^0.12.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  synchronized: ^3.0.0
  transparent_image: ^2.0.0
  uuid: ^3.0.4
  webview_flutter: ^2.0.10

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.1.0
  file: ^6.1.0
  flutter_launcher_icons: ^0.9.1
  mockito: ^5.0.13
  sqflite_common_ffi: ^2.0.0+1

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
