name: seagull
description: The seagull app.
version: 1.2.0
publish_to: none

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.14.12
  devicelocale: ^0.4.0
  dotted_border: ^2.0.0-nullsafety.0
  dotted_line: ^2.0.2 # no ns 2021-03-09
  equatable: ^2.0.0
  exif: ^1.0.3 # no ns 2021-03-09
  firebase_analytics: ^7.0.0 # ^7.1.0
  firebase_core: ^0.6.0 # ^1.0.0
  firebase_crashlytics: ^0.3.0 # ^1.0.0
  firebase_messaging: ^8.0.0-dev.12 # ^9.0.0
  flutter_appcenter_bundle: 3.2.0+2 # no ns 2021-03-09
  flutter_archive: ^3.0.0
  flutter_bloc: ^6.1.3 # ^7.0.0-nullsafety.4
  flutter_local_notifications:
    git:
      url: git://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v3.0.3-fork-1.8 # flutter_local_notifications-v5.0.0-nullsafety.1-fork-1.9
      path: flutter_local_notifications/
  flutter_native_timezone: ^1.0.10
  flutter_tts: ^3.0.0
  get_it: ^6.0.0
  google_fonts: ^1.1.2 # ^2.0.0
  http: ^0.12.2 # ^0.13.0
  image_picker: ^0.6.7+22 # ^0.7.2
  logging: ^1.0.0
  meta: ^1.1.8
  mime: ^1.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler:
    git:
      url: git://github.com/abilia/flutter-permission-handler.git
      ref: permission_handler_v5.1.0+10+fork.2 # permission_handler_v6.0.1+fork
      path: permission_handler/
  photo_view: ^0.11.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.3
  sqflite: ^2.0.0+2
  synchronized: ^3.0.0
  transparent_image: ^2.0.0-nullsafety.0
  uuid: ^2.2.2 # ^3.0.1

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.5 # no ns 2021-03-09
  file: ^6.0.0
  flutter_launcher_icons: ^0.8.1 # ^0.9.0
  mockito: ^4.1.4 # ^0.5.0
  sqflite_common_ffi: ^2.0.0

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
