name: seagull
description: The seagull app.
version: 4.1.0
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  acapela_tts:
    git:
      url: https://github.com/abilia/acapela_tts.git
      ref: v1.1.3
  android_intent_plus: ^3.0.1
  audioplayers: ^1.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  battery_plus: ^2.0.1
  bloc_concurrency: ^0.2.0
  collection: ^1.15.0
  connectivity_plus: ^2.1.0
  crypto: ^3.0.1
  device_info_plus: ^4.0.2
  devicelocale: ^0.5.0
  dotted_border: ^2.0.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  firebase_analytics: ^9.1.2
  firebase_core: ^1.8.0
  firebase_crashlytics: ^2.2.4
  firebase_messaging: ^12.0.1
  flutter:
    sdk: flutter
  flutter_archive: ^4.2.2
  flutter_bloc: ^8.0.1
  flutter_local_notifications:
    git:
      url: https://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v9.8.0+1-fork-2.6
      path: flutter_local_notifications/
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_ringtone_player: ^3.1.0
  flutter_tts: ^3.2.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  image: ^3.2.0
  image_picker: ^0.8.4
  intl: ^0.17.0
  logging: ^1.0.1
  matrix4_transform: ^2.0.1
  meta: ^1.7.0
  mime: ^1.0.1
  package_info: ^2.0.2
  path: ^1.8.1
  path_provider: ^2.0.5
  permission_handler: ^10.0.0
  photo_view: ^0.14.0
  provider: ^6.0.3
  record: ^4.3.2
  rxdart: ^0.27.1
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.1.1+1
  synchronized: ^3.0.0
  system_settings_editor:
    git:
      url: https://github.com/abilia/system_settings_editor.git
      ref: v1.3.5
  timezone: ^0.8.0
  transparent_image: ^2.0.0
  uuid: ^3.0.5
  vector_math: ^2.1.2
  wakelock: ^0.6.1
  webview_flutter: ^3.0.1
  youtube_player_iframe: ^3.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build: any
  build_runner: ^2.1.4
  built_collection: any
  code_builder: any
  dart_style: any
  file: ^6.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  test: any

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
