name: seagull
description: The seagull app.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^5.4.2
  flutter_bloc: ^4.0.0
  meta: ^1.1.8
  equatable: ^1.1.1
  http: ^0.12.0+4
  uuid: ^2.0.4
  firebase_messaging:
    git:
      url: git://github.com/abilia/flutterfire.git
      ref: ios-background-support
      path: packages/firebase_messaging/
  sqflite: ^1.2.2
  get_it: ^4.0.2
  shared_preferences: ^0.5.6+2
  path_provider: ^1.6.5
  package_info: ^0.4.0+14
  flutter_local_notifications:
    git:
      url: git://github.com/abilia/flutter_local_notifications.git
      ref: dev-1.4.4+1
      path: flutter_local_notifications/
  transparent_image: ^1.0.0
  rxdart: ^0.24.1
  dotted_border: ^1.0.5
  synchronized: ^2.2.0
  image_picker: ^0.6.3+4
  mime: ^0.9.6+3
  exif: ^1.0.2
  devicelocale: ^0.2.3
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  collection: ^1.14.12
  flutter_advanced_networkimage: ^0.7.0
  flutter_appcenter_bundle: 3.2.0+1
  logging: ^0.11.4
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  mockito: ^4.1.1
  flutter_driver:
    sdk: flutter
  test: any
  file: ^5.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
