name: seagull_fakes

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  abilia_sync:
    path: ../abilia_sync
  auth:
    path: ../auth
  bloc_test: any
  calendar:
    path: ../calendar
  file_storage:
    path: ../file_storage
  flutter:
    sdk: flutter
  http: any
  mocktail: any
  repository_base:
    path: ../repository/repository_base
  seagull_analytics:
    path: ../seagull_analytics
  shared_preferences: any
  sortables:
    path: ../sortables
  sqflite: any
  user_files:
    path: ../user_files
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  seagull_lints:
    path: ../seagull_lints
