name: text_to_speech

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  acapela_tts:
    git:
      url: https://github.com/abilia/acapela_tts.git
      ref: v1.1.3
  flutter_tts: ^3.6.0
  logging: any

dev_dependencies:
  seagull_lints:
    path: ../seagull_lints
