name: text_to_speech

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  acapela_tts:
    path: ../acapela_tts
  collection: any
  crypto: any
  equatable: any
  flutter_archive: any
  flutter_bloc: any
  flutter_tts: ^3.6.0
  http: any
  logging: any
  path: any
  repository_base:
    path: ../repository_base
  shared_preferences: any
  utils:
    path: ../utils

dev_dependencies:
  seagull_lints:
    path: ../seagull_lints
