name: memoplanner
description: MEMOplanner GO and MEMOPlanner 4
version: 4.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  abilia_sync:
    path: ../packages/abilia_sync
  android_intent_plus: ^4.0.1
  audioplayers: ^5.1.0
  auth:
    path: ../packages/auth
  auto_size_text: ^3.0.0
  battery_plus: ^4.0.1
  bloc_concurrency: ^0.2.0
  calendar:
    path: ../packages/calendar
  calendar_events:
    path: ../packages/calendar_events
  collection: ^1.17.0
  connectivity:
    path: ../packages/connectivity
  connectivity_plus: ^4.0.1
  crypto: ^3.0.1
  device_info_plus: ^8.0.0
  dotted_border: ^2.0.0
  envied: ^0.3.0
  equatable: ^2.0.3
  file_storage:
    path: ../packages/file_storage
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_bloc: ^8.0.1
  flutter_isolate: ^2.0.3
  flutter_local_notifications:
    git:
      url: https://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v14.1.0-fork-3.5
      path: flutter_local_notifications/
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_ringtone_player: ^3.1.0
  generics:
    path: ../packages/generics
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^1.0.2
  intl: ^0.18.0
  logging: ^1.1.0
  lokalise_flutter_sdk: ^1.1.1
  matrix4_transform: ^2.0.1
  meta: ^1.7.0
  mime: ^1.0.1
  murmurhash: ^1.0.1
  package_info_plus: ^3.0.3
  path: ^1.8.1
  path_provider: ^2.0.5
  permission_handler: ^10.2.0
  permissions:
    path: ../packages/permissions
  photo_view: ^0.14.0
  provider: ^6.0.4
  record: ^4.4.3
  repository_base:
    path: ../packages/repository_base
  rxdart: ^0.27.1
  seagull_analytics:
    path: ../packages/seagull_analytics
  seagull_clock:
    path: ../packages/seagull_clock
  seagull_logging:
    path: ../packages/seagull_logging
  shared_preferences: ^2.0.8
  sortables:
    path: ../packages/sortables
  sqflite: ^2.2.5
  sqflite_common_ffi: ^2.2.5
  support_persons:
    path: ../packages/support_persons
  synchronized: ^3.0.0
  system_settings_editor:
    git:
      url: https://github.com/abilia/system_settings_editor.git
      ref: v1.3.7
  text_to_speech:
    path: ../packages/text_to_speech
  timezone: ^0.9.0
  transparent_image: ^2.0.0
  user_files:
    path: ../packages/user_files
  utils:
    path: ../packages/utils
  uuid: ^3.0.5
  vector_math: ^2.1.2
  video_compress: ^3.1.2
  video_player: ^2.6.0
  wakelock: ^0.6.1
  webview_flutter: ^4.0.4
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.3.0
  envied_generator: ^0.3.0
  file: ^6.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0
  seagull_fakes:
    path: ../packages/seagull_fakes
  seagull_lints:
    path: ../packages/seagull_lints
  test: any

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
