name: memoplanner
description: The seagull app.
version: 4.2.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  acapela_tts:
    git:
      url: https://github.com/abilia/acapela_tts.git
      ref: v1.1.3
  android_intent_plus: ^3.1.5
  audioplayers: ^3.0.1
  auto_size_text: ^3.0.0
  battery_plus: ^3.0.2
  bloc_concurrency: ^0.2.0
  collection: ^1.17.0
  connectivity_plus: ^3.0.2
  crypto: ^3.0.1
  device_info_plus: ^8.0.0
  devicelocale: ^0.6.0
  dotted_border: ^2.0.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.0.4
  flutter:
    sdk: flutter
  flutter_archive: ^4.2.2
  flutter_bloc: ^8.0.1
  flutter_isolate: ^2.0.3
  flutter_local_notifications:
    git:
      url: https://github.com/abilia/flutter_local_notifications.git
      ref: flutter_local_notifications-v12.0.2-fork-3.1
      path: flutter_local_notifications/
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  flutter_ringtone_player: ^3.1.0
  flutter_tts: ^3.6.0
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  image: ^4.0.15
  image_picker: ^0.8.6
  intl: ^0.17.0
  logging: ^1.1.0
  matrix4_transform: ^2.0.1
  meta: ^1.7.0
  mime: ^1.0.1
  murmurhash: ^1.0.1
  package_info_plus: ^3.0.3
  path: ^1.8.1
  path_provider: ^2.0.5
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.4
  record: ^4.4.3
  rxdart: ^0.27.1
  seagull_analytics:
    path: ../packages/seagull_analytics
  shared_preferences: ^2.0.8
  sqflite: ^2.2.0
  sqflite_common_ffi: ^2.2.0
  synchronized: ^3.0.0
  system_settings_editor:
    git:
      url: https://github.com/abilia/system_settings_editor.git
      ref: v1.3.7
  timezone: ^0.9.0
  transparent_image: ^2.0.0
  uuid: ^3.0.5
  vector_math: ^2.1.2
  wakelock: ^0.6.1
  webview_flutter: ^4.0.4
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.3.0
  file: ^6.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  seagull_lints:
    path: ../packages/seagull_lints
  test: any
  translation_generator:
    path: ../packages/translation_generator

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/MEMOplannerGO_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/graphics/memoplanner/
    - assets/graphics/memoplannergo/
    - google_fonts/
    - assets/sounds/
  fonts:
    - family: AbiliaFont
      fonts:
        - asset: assets/fonts/AbiliaFont.ttf
