name: database

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'


dependencies:
  collection: ^1.17.0
  path: ^1.8.1
  sqflite: ^2.2.0
  sqflite_common_ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  seagull_lints:
    path: ../seagull_lints
  test: any
