name: auth

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  calendar:
    path: ../calendar
  collection: ^1.17.0
  equatable: ^2.0.3
  firebase_messaging: ^14.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  logging: ^1.1.0
  meta: ^1.7.0
  repository_base:
    path: ../repository/repository_base
  seagull_clock:
    path: ../seagull_clock
  shared_preferences: ^2.0.8
  sqflite: ^2.2.0
  synchronized: ^3.0.0
  utils:
    path: ../utils
  uuid: ^3.0.5

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  seagull_lints:
    path: ../seagull_lints
  test: any
