name: auth

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  database:
    path: ../database
  equatable: ^2.0.3
  logging: ^1.1.0
  repo_base:
    path: ../repo_base
  shared_preferences: ^2.0.8
  sqflite: ^2.2.0
  utils:
    path: ../utils
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.5
  mocktail: ^0.3.0
  seagull_lints:
    path: ../seagull_lints
  test: any
