name: file_storage

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  equatable: any
  seagull_logging:
    path: ../seagull_logging

dev_dependencies:
  seagull_lints:
    path: ../seagull_lints
