name: seagull_analytics

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  equatable: any
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: any
  mixpanel_flutter: ^2.0.0
  seagull_lints:
    path: ../seagull_lints
