name: seagull_analytics

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  logging: ^1.1.0
  mixpanel_flutter: ^2.0.0
  equatable: ^2.0.3
