import 'package:flutter/foundation.dart';

class TestKey {
  static const Key userNameInput = Key('userName'),
      passwordInput = Key('password'),
      hidePasswordToggle = Key('hidePassword'),
      loggInButton = Key('loggIn'),
      loginError = Key('loginError'),
      goToNowButton = Key('goToNow'),
      onScreenAlarm = Key('onScreenAlarm'),
      onScreenReminder = Key('onScreenReminder'),
      appBarCloseButton = Key('appBarCloseButton'),
      showAllFullDays = Key('showAllFullDays'),
      changeView = Key('changeView'),
      timePillarButton = Key('timePillarButton'),
      activityBackButton = Key('activityBackButton'),
      activityUncheckButton = Key('activityUncheckButton'),
      activityCheckButton = Key('activityCheckButton'),
      attachment = Key('attachment'),
      addActivity = Key('addActivity'),
      newActivityNameInput = Key('newActivityNameInput'),
      finishNewActivityButton = Key('finishNewActivityButton'),
      fullDaySwitch = Key('fullDaySwitch'),
      datePicker = Key('datePicker'),
      startTimePicker = Key('startTimePicker'),
      endTimePicker = Key('endTimePicker'),
      rightCategoryRadio = Key('rightCategoryRadio'),
      leftCategoryRadio = Key('leftCategoryRadio'),
      alarmAtStartSwitch = Key('alarmAtStartSwitch'),
      checkableSwitch = Key('checkableSwitch');
}
