// Mocks generated by Mockito 5.0.15 from annotations
// in seagull/test/mocks/shared.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;
import 'dart:convert' as _i23;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i22;
import 'dart:ui' as _i21;

import 'package:bloc/bloc.dart' as _i20;
import 'package:flutter/material.dart' as _i12;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i14;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i15;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i17;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i18;
import 'package:flutter_local_notifications/src/types.dart' as _i19;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i16;
import 'package:http/http.dart' as _i5;
import 'package:logging/logging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i2;
import 'package:seagull/bloc/activities/edit_recurring_mixin.dart' as _i11;
import 'package:seagull/bloc/all.dart' as _i10;
import 'package:seagull/db/all.dart' as _i3;
import 'package:seagull/models/all.dart' as _i1;
import 'package:seagull/repository/all.dart' as _i6;
import 'package:seagull/storage/all.dart' as _i7;
import 'package:shared_preferences/shared_preferences.dart' as _i13;

import 'shared.dart' as _i24;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDataDb_0<M extends _i1.DataModel> extends _i2.Fake
    implements _i3.DataDb<M> {}

class _FakeLogger_1 extends _i2.Fake implements _i4.Logger {}

class _FakeDbModel_2<M extends _i1.DataModel> extends _i2.Fake
    implements _i1.DbModel<M> {}

class _FakeBaseClient_3 extends _i2.Fake implements _i5.BaseClient {}

class _FakeDataUpdateResponse_4 extends _i2.Fake
    implements _i1.DataUpdateResponse {}

class _FakeTokenDb_5 extends _i2.Fake implements _i3.TokenDb {}

class _FakeUserDb_6 extends _i2.Fake implements _i3.UserDb {}

class _FakeLicenseDb_7 extends _i2.Fake implements _i3.LicenseDb {}

class _FakeUserRepository_8 extends _i2.Fake implements _i6.UserRepository {}

class _FakeUser_9 extends _i2.Fake implements _i1.User {}

class _FakeUserFileDb_10 extends _i2.Fake implements _i3.UserFileDb {}

class _FakeFileStorage_11 extends _i2.Fake implements _i7.FileStorage {}

class _FakeMultipartRequestBuilder_12 extends _i2.Fake
    implements _i6.MultipartRequestBuilder {}

class _FakeFile_13 extends _i2.Fake implements _i8.File {}

class _FakeActivityRepository_14 extends _i2.Fake
    implements _i6.ActivityRepository {}

class _FakeStreamSubscription_15<T> extends _i2.Fake
    implements _i9.StreamSubscription<T> {}

class _FakeSyncBloc_16 extends _i2.Fake implements _i10.SyncBloc {}

class _FakeActivitiesState_17 extends _i2.Fake implements _i10.ActivitiesState {
}

class _FakeActivityMappingResult_18 extends _i2.Fake
    implements _i11.ActivityMappingResult {}

class _FakeUserFileRepository_19 extends _i2.Fake
    implements _i6.UserFileRepository {}

class _FakeSortableRepository_20 extends _i2.Fake
    implements _i6.SortableRepository {}

class _FakeGenericRepository_21 extends _i2.Fake
    implements _i6.GenericRepository {}

class _FakeSyncDelays_22 extends _i2.Fake implements _i10.SyncDelays {}

class _FakeSyncState_23 extends _i2.Fake implements _i10.SyncState {}

class _FakePushState_24 extends _i2.Fake implements _i10.PushState {}

class _FakeGenericState_25 extends _i2.Fake implements _i10.GenericState {}

class _FakeScrollPosition_26 extends _i2.Fake implements _i12.ScrollPosition {}

class _FakeMultipartRequest_27 extends _i2.Fake
    implements _i5.MultipartRequest {}

class _FakeUri_28 extends _i2.Fake implements Uri {}

class _FakeByteStream_29 extends _i2.Fake implements _i5.ByteStream {}

class _FakeStreamedResponse_30 extends _i2.Fake
    implements _i5.StreamedResponse {}

class _FakeBatch_31 extends _i2.Fake implements _i3.Batch {}

class _FakeResponse_32 extends _i2.Fake implements _i5.Response {}

class _FakeSharedPreferences_33 extends _i2.Fake
    implements _i13.SharedPreferences {}

class _FakeDatabase_34 extends _i2.Fake implements _i3.Database {}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i2.Mock
    implements _i6.ActivityRepository {
  MockActivityRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i3.DataDb<_i1.Activity> get db => (super.noSuchMethod(Invocation.getter(#db),
      returnValue: _FakeDataDb_0<_i1.Activity>()) as _i3.DataDb<_i1.Activity>);
  @override
  String get authToken =>
      (super.noSuchMethod(Invocation.getter(#authToken), returnValue: '')
          as String);
  @override
  int get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: 0) as int);
  @override
  _i4.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_1())
          as _i4.Logger);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  String get postPath =>
      (super.noSuchMethod(Invocation.getter(#postPath), returnValue: '')
          as String);
  @override
  int get postApiVersion =>
      (super.noSuchMethod(Invocation.getter(#postApiVersion), returnValue: 0)
          as int);
  @override
  _i6.JsonToDataModel<_i1.Activity> get fromJsonToDataModel =>
      (super.noSuchMethod(Invocation.getter(#fromJsonToDataModel),
              returnValue: (Map<String, dynamic> json) =>
                  _FakeDbModel_2<_i1.Activity>())
          as _i6.JsonToDataModel<_i1.Activity>);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i5.BaseClient get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeBaseClient_3()) as _i5.BaseClient);
  @override
  _i9.Future<bool> save(Iterable<_i1.Activity>? data) =>
      (super.noSuchMethod(Invocation.method(#save, [data]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<Iterable<_i1.Activity>> load() => (super.noSuchMethod(
          Invocation.method(#load, []),
          returnValue: Future<Iterable<_i1.Activity>>.value(<_i1.Activity>[]))
      as _i9.Future<Iterable<_i1.Activity>>);
  @override
  _i9.Future<dynamic> fetchIntoDatabaseSynchronized() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabaseSynchronized, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> fetchIntoDatabase() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabase, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<Iterable<_i1.DbModel<_i1.Activity>>> fetchData(int? revision) =>
      (super.noSuchMethod(Invocation.method(#fetchData, [revision]),
              returnValue: Future<Iterable<_i1.DbModel<_i1.Activity>>>.value(
                  <_i1.DbModel<_i1.Activity>>[]))
          as _i9.Future<Iterable<_i1.DbModel<_i1.Activity>>>);
  @override
  _i9.Future<bool> synchronize() =>
      (super.noSuchMethod(Invocation.method(#synchronize, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i1.DataUpdateResponse> postData(
          Iterable<_i1.DbModel<_i1.Activity>>? data) =>
      (super.noSuchMethod(Invocation.method(#postData, [data]),
              returnValue: Future<_i1.DataUpdateResponse>.value(
                  _FakeDataUpdateResponse_4()))
          as _i9.Future<_i1.DataUpdateResponse>);
  @override
  _i9.Future<dynamic> handleFailedSync(
          Iterable<_i1.DataRevisionUpdate>? failed) =>
      (super.noSuchMethod(Invocation.method(#handleFailedSync, [failed]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> handleSuccessfullSync(
          Iterable<_i1.DataRevisionUpdate>? succeeded,
          Iterable<_i1.DbModel<_i1.Activity>>? dirtyData) =>
      (super.noSuchMethod(
          Invocation.method(#handleSuccessfullSync, [succeeded, dirtyData]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i2.Mock implements _i6.UserRepository {
  MockUserRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i3.TokenDb get tokenDb => (super.noSuchMethod(Invocation.getter(#tokenDb),
      returnValue: _FakeTokenDb_5()) as _i3.TokenDb);
  @override
  _i3.UserDb get userDb => (super.noSuchMethod(Invocation.getter(#userDb),
      returnValue: _FakeUserDb_6()) as _i3.UserDb);
  @override
  _i3.LicenseDb get licenseDb =>
      (super.noSuchMethod(Invocation.getter(#licenseDb),
          returnValue: _FakeLicenseDb_7()) as _i3.LicenseDb);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i5.BaseClient get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeBaseClient_3()) as _i5.BaseClient);
  @override
  _i6.UserRepository copyWith({String? baseUrl, _i5.BaseClient? client}) =>
      (super.noSuchMethod(
          Invocation.method(
              #copyWith, [], {#baseUrl: baseUrl, #client: client}),
          returnValue: _FakeUserRepository_8()) as _i6.UserRepository);
  @override
  _i9.Future<String> authenticate(
          {String? username,
          String? password,
          String? pushToken,
          DateTime? time}) =>
      (super.noSuchMethod(
          Invocation.method(#authenticate, [], {
            #username: username,
            #password: password,
            #pushToken: pushToken,
            #time: time
          }),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i1.User> me(String? token) =>
      (super.noSuchMethod(Invocation.method(#me, [token]),
              returnValue: Future<_i1.User>.value(_FakeUser_9()))
          as _i9.Future<_i1.User>);
  @override
  _i9.Future<_i1.User> getUserFromDb() =>
      (super.noSuchMethod(Invocation.method(#getUserFromDb, []),
              returnValue: Future<_i1.User>.value(_FakeUser_9()))
          as _i9.Future<_i1.User>);
  @override
  _i9.Future<_i1.User> getUserFromApi(String? token) =>
      (super.noSuchMethod(Invocation.method(#getUserFromApi, [token]),
              returnValue: Future<_i1.User>.value(_FakeUser_9()))
          as _i9.Future<_i1.User>);
  @override
  _i9.Future<List<_i1.License>> getLicenses() =>
      (super.noSuchMethod(Invocation.method(#getLicenses, []),
              returnValue: Future<List<_i1.License>>.value(<_i1.License>[]))
          as _i9.Future<List<_i1.License>>);
  @override
  _i9.Future<List<_i1.License>> getLicensesFromApi(String? token) =>
      (super.noSuchMethod(Invocation.method(#getLicensesFromApi, [token]),
              returnValue: Future<List<_i1.License>>.value(<_i1.License>[]))
          as _i9.Future<List<_i1.License>>);
  @override
  _i9.Future<dynamic> logout([String? token]) =>
      (super.noSuchMethod(Invocation.method(#logout, [token]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<void> persistToken(String? token) =>
      (super.noSuchMethod(Invocation.method(#persistToken, [token]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> createAccount(
          {String? language,
          String? usernameOrEmail,
          String? password,
          bool? termsOfUse,
          bool? privacyPolicy}) =>
      (super.noSuchMethod(
          Invocation.method(#createAccount, [], {
            #language: language,
            #usernameOrEmail: usernameOrEmail,
            #password: password,
            #termsOfUse: termsOfUse,
            #privacyPolicy: privacyPolicy
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SortableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSortableRepository extends _i2.Mock
    implements _i6.SortableRepository {
  MockSortableRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i3.DataDb<_i1.Sortable<_i1.SortableData>> get db =>
      (super.noSuchMethod(Invocation.getter(#db),
              returnValue: _FakeDataDb_0<_i1.Sortable<_i1.SortableData>>())
          as _i3.DataDb<_i1.Sortable<_i1.SortableData>>);
  @override
  String get authToken =>
      (super.noSuchMethod(Invocation.getter(#authToken), returnValue: '')
          as String);
  @override
  int get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: 0) as int);
  @override
  _i4.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_1())
          as _i4.Logger);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  String get postPath =>
      (super.noSuchMethod(Invocation.getter(#postPath), returnValue: '')
          as String);
  @override
  int get postApiVersion =>
      (super.noSuchMethod(Invocation.getter(#postApiVersion), returnValue: 0)
          as int);
  @override
  _i6.JsonToDataModel<_i1.Sortable<_i1.SortableData>> get fromJsonToDataModel =>
      (super.noSuchMethod(Invocation.getter(#fromJsonToDataModel),
              returnValue: (Map<String, dynamic> json) =>
                  _FakeDbModel_2<_i1.Sortable<_i1.SortableData>>())
          as _i6.JsonToDataModel<_i1.Sortable<_i1.SortableData>>);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i5.BaseClient get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeBaseClient_3()) as _i5.BaseClient);
  @override
  _i9.Future<bool> save(Iterable<_i1.Sortable<_i1.SortableData>>? data) =>
      (super.noSuchMethod(Invocation.method(#save, [data]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<Iterable<_i1.Sortable<_i1.SortableData>>> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
          returnValue: Future<Iterable<_i1.Sortable<_i1.SortableData>>>.value(
              <_i1.Sortable<_i1.SortableData>>[])) as _i9
          .Future<Iterable<_i1.Sortable<_i1.SortableData>>>);
  @override
  _i9.Future<dynamic> fetchIntoDatabaseSynchronized() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabaseSynchronized, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> fetchIntoDatabase() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabase, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<Iterable<_i1.DbModel<_i1.Sortable<_i1.SortableData>>>> fetchData(
          int? revision) =>
      (super.noSuchMethod(Invocation.method(#fetchData, [revision]),
          returnValue: Future<
                  Iterable<_i1.DbModel<_i1.Sortable<_i1.SortableData>>>>.value(
              <_i1.DbModel<_i1.Sortable<_i1.SortableData>>>[])) as _i9
          .Future<Iterable<_i1.DbModel<_i1.Sortable<_i1.SortableData>>>>);
  @override
  _i9.Future<bool> synchronize() =>
      (super.noSuchMethod(Invocation.method(#synchronize, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i1.DataUpdateResponse> postData(
          Iterable<_i1.DbModel<_i1.Sortable<_i1.SortableData>>>? data) =>
      (super.noSuchMethod(Invocation.method(#postData, [data]),
              returnValue: Future<_i1.DataUpdateResponse>.value(
                  _FakeDataUpdateResponse_4()))
          as _i9.Future<_i1.DataUpdateResponse>);
  @override
  _i9.Future<dynamic> handleFailedSync(
          Iterable<_i1.DataRevisionUpdate>? failed) =>
      (super.noSuchMethod(Invocation.method(#handleFailedSync, [failed]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> handleSuccessfullSync(
          Iterable<_i1.DataRevisionUpdate>? succeeded,
          Iterable<_i1.DbModel<_i1.Sortable<_i1.SortableData>>>? dirtyData) =>
      (super.noSuchMethod(
          Invocation.method(#handleSuccessfullSync, [succeeded, dirtyData]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserFileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFileRepository extends _i2.Mock
    implements _i6.UserFileRepository {
  MockUserFileRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i3.UserFileDb get userFileDb =>
      (super.noSuchMethod(Invocation.getter(#userFileDb),
          returnValue: _FakeUserFileDb_10()) as _i3.UserFileDb);
  @override
  _i7.FileStorage get fileStorage =>
      (super.noSuchMethod(Invocation.getter(#fileStorage),
          returnValue: _FakeFileStorage_11()) as _i7.FileStorage);
  @override
  _i6.MultipartRequestBuilder get multipartRequestBuilder =>
      (super.noSuchMethod(Invocation.getter(#multipartRequestBuilder),
              returnValue: _FakeMultipartRequestBuilder_12())
          as _i6.MultipartRequestBuilder);
  @override
  _i3.DataDb<_i1.UserFile> get db => (super.noSuchMethod(Invocation.getter(#db),
      returnValue: _FakeDataDb_0<_i1.UserFile>()) as _i3.DataDb<_i1.UserFile>);
  @override
  String get authToken =>
      (super.noSuchMethod(Invocation.getter(#authToken), returnValue: '')
          as String);
  @override
  int get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: 0) as int);
  @override
  _i4.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_1())
          as _i4.Logger);
  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  String get postPath =>
      (super.noSuchMethod(Invocation.getter(#postPath), returnValue: '')
          as String);
  @override
  int get postApiVersion =>
      (super.noSuchMethod(Invocation.getter(#postApiVersion), returnValue: 0)
          as int);
  @override
  _i6.JsonToDataModel<_i1.UserFile> get fromJsonToDataModel =>
      (super.noSuchMethod(Invocation.getter(#fromJsonToDataModel),
              returnValue: (Map<String, dynamic> json) =>
                  _FakeDbModel_2<_i1.UserFile>())
          as _i6.JsonToDataModel<_i1.UserFile>);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i5.BaseClient get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeBaseClient_3()) as _i5.BaseClient);
  @override
  _i9.Future<Iterable<_i1.UserFile>> getAllLoadedFiles() => (super.noSuchMethod(
          Invocation.method(#getAllLoadedFiles, []),
          returnValue: Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[]))
      as _i9.Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<Iterable<_i1.UserFile>> load() => (super.noSuchMethod(
          Invocation.method(#load, []),
          returnValue: Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[]))
      as _i9.Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<bool> synchronize() =>
      (super.noSuchMethod(Invocation.method(#synchronize, []),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<Iterable<_i1.UserFile>> downloadUserFiles({int? limit}) => (super
      .noSuchMethod(Invocation.method(#downloadUserFiles, [], {#limit: limit}),
          returnValue:
              Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[])) as _i9
      .Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<bool> save(Iterable<_i1.UserFile>? data) =>
      (super.noSuchMethod(Invocation.method(#save, [data]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<dynamic> fetchIntoDatabaseSynchronized() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabaseSynchronized, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> fetchIntoDatabase() =>
      (super.noSuchMethod(Invocation.method(#fetchIntoDatabase, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<Iterable<_i1.DbModel<_i1.UserFile>>> fetchData(int? revision) =>
      (super.noSuchMethod(Invocation.method(#fetchData, [revision]),
              returnValue: Future<Iterable<_i1.DbModel<_i1.UserFile>>>.value(
                  <_i1.DbModel<_i1.UserFile>>[]))
          as _i9.Future<Iterable<_i1.DbModel<_i1.UserFile>>>);
  @override
  _i9.Future<_i1.DataUpdateResponse> postData(
          Iterable<_i1.DbModel<_i1.UserFile>>? data) =>
      (super.noSuchMethod(Invocation.method(#postData, [data]),
              returnValue: Future<_i1.DataUpdateResponse>.value(
                  _FakeDataUpdateResponse_4()))
          as _i9.Future<_i1.DataUpdateResponse>);
  @override
  _i9.Future<dynamic> handleFailedSync(
          Iterable<_i1.DataRevisionUpdate>? failed) =>
      (super.noSuchMethod(Invocation.method(#handleFailedSync, [failed]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> handleSuccessfullSync(
          Iterable<_i1.DataRevisionUpdate>? succeeded,
          Iterable<_i1.DbModel<_i1.UserFile>>? dirtyData) =>
      (super.noSuchMethod(
          Invocation.method(#handleSuccessfullSync, [succeeded, dirtyData]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FirebasePushService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebasePushService extends _i2.Mock
    implements _i6.FirebasePushService {
  MockFirebasePushService() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String?> initPushToken() =>
      (super.noSuchMethod(Invocation.method(#initPushToken, []),
          returnValue: Future<String?>.value()) as _i9.Future<String?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FileStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileStorage extends _i2.Mock implements _i7.FileStorage {
  MockFileStorage() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get fileEnding =>
      (super.noSuchMethod(Invocation.getter(#fileEnding), returnValue: '')
          as String);
  @override
  int get maxSizeInBytes =>
      (super.noSuchMethod(Invocation.getter(#maxSizeInBytes), returnValue: 0)
          as int);
  @override
  _i9.Future<void> storeFile(List<int>? fileBytes, String? fileName) =>
      (super.noSuchMethod(Invocation.method(#storeFile, [fileBytes, fileName]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> storeImageThumb(
          List<int>? fileBytes, _i1.ImageThumb? imageThumb) =>
      (super.noSuchMethod(
          Invocation.method(#storeImageThumb, [fileBytes, imageThumb]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i8.File getFile(String? id) =>
      (super.noSuchMethod(Invocation.method(#getFile, [id]),
          returnValue: _FakeFile_13()) as _i8.File);
  @override
  _i8.File getImageThumb(_i1.ImageThumb? imageThumb) =>
      (super.noSuchMethod(Invocation.method(#getImageThumb, [imageThumb]),
          returnValue: _FakeFile_13()) as _i8.File);
  @override
  _i9.Future<dynamic> deleteUserFolder() =>
      (super.noSuchMethod(Invocation.method(#deleteUserFolder, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<bool> exists(_i8.File? file) =>
      (super.noSuchMethod(Invocation.method(#exists, [file]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i8.File?> copyImageThumbForNotification(String? id) => (super
      .noSuchMethod(Invocation.method(#copyImageThumbForNotification, [id]),
          returnValue: Future<_i8.File?>.value()) as _i9.Future<_i8.File?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i2.Mock
    implements _i14.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i9.Future<bool?> initialize(
          _i15.InitializationSettings? initializationSettings,
          {_i16.SelectNotificationCallback? onSelectNotification}) =>
      (super.noSuchMethod(
          Invocation.method(#initialize, [initializationSettings],
              {#onSelectNotification: onSelectNotification}),
          returnValue: Future<bool?>.value()) as _i9.Future<bool?>);
  @override
  _i9.Future<_i16.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
              Invocation.method(#getNotificationAppLaunchDetails, []),
              returnValue: Future<_i16.NotificationAppLaunchDetails?>.value())
          as _i9.Future<_i16.NotificationAppLaunchDetails?>);
  @override
  _i9.Future<void> show(int? id, String? title, String? body,
          _i17.NotificationDetails? notificationDetails, {String? payload}) =>
      (super.noSuchMethod(
          Invocation.method(#show, [id, title, body, notificationDetails],
              {#payload: payload}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(Invocation.method(#cancel, [id], {#tag: tag}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> cancelAll() =>
      (super.noSuchMethod(Invocation.method(#cancelAll, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> schedule(
          int? id,
          String? title,
          String? body,
          DateTime? scheduledDate,
          _i17.NotificationDetails? notificationDetails,
          {String? payload,
          bool? androidAllowWhileIdle = false}) =>
      (super.noSuchMethod(
          Invocation.method(#schedule, [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails
          ], {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> zonedSchedule(
          int? id,
          String? title,
          String? body,
          _i6.TZDateTime? scheduledDate,
          _i17.NotificationDetails? notificationDetails,
          {_i18.UILocalNotificationDateInterpretation?
              uiLocalNotificationDateInterpretation,
          bool? androidAllowWhileIdle,
          String? payload,
          _i19.DateTimeComponents? matchDateTimeComponents}) =>
      (super.noSuchMethod(
          Invocation.method(#zonedSchedule, [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails
          ], {
            #uiLocalNotificationDateInterpretation:
                uiLocalNotificationDateInterpretation,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> periodicallyShow(
          int? id,
          String? title,
          String? body,
          _i16.RepeatInterval? repeatInterval,
          _i17.NotificationDetails? notificationDetails,
          {String? payload,
          bool? androidAllowWhileIdle = false}) =>
      (super.noSuchMethod(
          Invocation.method(#periodicallyShow, [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails
          ], {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> showDailyAtTime(
          int? id,
          String? title,
          String? body,
          _i19.Time? notificationTime,
          _i17.NotificationDetails? notificationDetails,
          {String? payload}) =>
      (super.noSuchMethod(
          Invocation.method(
              #showDailyAtTime,
              [id, title, body, notificationTime, notificationDetails],
              {#payload: payload}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<void> showWeeklyAtDayAndTime(
          int? id,
          String? title,
          String? body,
          _i19.Day? day,
          _i19.Time? notificationTime,
          _i17.NotificationDetails? notificationDetails,
          {String? payload}) =>
      (super.noSuchMethod(
          Invocation.method(
              #showWeeklyAtDayAndTime,
              [id, title, body, day, notificationTime, notificationDetails],
              {#payload: payload}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<List<_i16.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
              Invocation.method(#pendingNotificationRequests, []),
              returnValue: Future<List<_i16.PendingNotificationRequest>>.value(
                  <_i16.PendingNotificationRequest>[]))
          as _i9.Future<List<_i16.PendingNotificationRequest>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ActivitiesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivitiesBloc extends _i2.Mock implements _i10.ActivitiesBloc {
  MockActivitiesBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i6.ActivityRepository get activityRepository =>
      (super.noSuchMethod(Invocation.getter(#activityRepository),
          returnValue: _FakeActivityRepository_14()) as _i6.ActivityRepository);
  @override
  _i9.StreamSubscription<dynamic> get pushSubscription =>
      (super.noSuchMethod(Invocation.getter(#pushSubscription),
              returnValue: _FakeStreamSubscription_15<dynamic>())
          as _i9.StreamSubscription<dynamic>);
  @override
  set pushSubscription(_i9.StreamSubscription<dynamic>? _pushSubscription) =>
      super.noSuchMethod(
          Invocation.setter(#pushSubscription, _pushSubscription),
          returnValueForMissingStub: null);
  @override
  _i10.SyncBloc get syncBloc =>
      (super.noSuchMethod(Invocation.getter(#syncBloc),
          returnValue: _FakeSyncBloc_16()) as _i10.SyncBloc);
  @override
  _i10.ActivitiesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeActivitiesState_17()) as _i10.ActivitiesState);
  @override
  _i9.Stream<_i10.ActivitiesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.ActivitiesState>.empty())
          as _i9.Stream<_i10.ActivitiesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i9.Stream<_i10.ActivitiesState> mapEventToState(
          _i10.ActivitiesEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i10.ActivitiesState>.empty())
          as _i9.Stream<_i10.ActivitiesState>);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void add(_i10.ActivitiesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i10.ActivitiesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<
      _i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>> transformEvents(
          _i9.Stream<_i10.ActivitiesEvent>? events,
          _i20.TransitionFunction<_i10.ActivitiesEvent, _i10.ActivitiesState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>.empty())
          as _i9.Stream<
              _i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>);
  @override
  void emit(_i10.ActivitiesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>
      transformTransitions(
              _i9.Stream<_i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue:
                      Stream<_i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>.empty())
              as _i9.Stream<
                  _i20.Transition<_i10.ActivitiesEvent, _i10.ActivitiesState>>);
  @override
  _i9.StreamSubscription<_i10.ActivitiesState> listen(
          void Function(_i10.ActivitiesState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_15<_i10.ActivitiesState>())
          as _i9.StreamSubscription<_i10.ActivitiesState>);
  @override
  void onChange(_i20.Change<_i10.ActivitiesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
  @override
  _i11.ActivityMappingResult deleteThisDayAndForwardToState(
          {_i1.Activity? activity,
          Set<_i1.Activity>? activities,
          DateTime? day}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteThisDayAndForwardToState, [],
                  {#activity: activity, #activities: activities, #day: day}),
              returnValue: _FakeActivityMappingResult_18())
          as _i11.ActivityMappingResult);
  @override
  _i11.ActivityMappingResult deleteOnlyThisDay(
          {_i1.Activity? activity,
          Set<_i1.Activity>? activities,
          DateTime? day}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteOnlyThisDay, [],
                  {#activity: activity, #activities: activities, #day: day}),
              returnValue: _FakeActivityMappingResult_18())
          as _i11.ActivityMappingResult);
  @override
  _i11.ActivityMappingResult updateThisDayAndForward(
          {_i1.Activity? activity,
          Set<_i1.Activity>? activities,
          DateTime? day}) =>
      (super.noSuchMethod(
              Invocation.method(#updateThisDayAndForward, [],
                  {#activity: activity, #activities: activities, #day: day}),
              returnValue: _FakeActivityMappingResult_18())
          as _i11.ActivityMappingResult);
  @override
  _i11.ActivityMappingResult updateOnlyThisDay(
          {_i1.Activity? activity,
          Set<_i1.Activity>? activities,
          DateTime? day}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOnlyThisDay, [],
                  {#activity: activity, #activities: activities, #day: day}),
              returnValue: _FakeActivityMappingResult_18())
          as _i11.ActivityMappingResult);
}

/// A class which mocks [SyncBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncBloc extends _i2.Mock implements _i10.SyncBloc {
  MockSyncBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i6.ActivityRepository get activityRepository =>
      (super.noSuchMethod(Invocation.getter(#activityRepository),
          returnValue: _FakeActivityRepository_14()) as _i6.ActivityRepository);
  @override
  _i6.UserFileRepository get userFileRepository =>
      (super.noSuchMethod(Invocation.getter(#userFileRepository),
          returnValue: _FakeUserFileRepository_19()) as _i6.UserFileRepository);
  @override
  _i6.SortableRepository get sortableRepository =>
      (super.noSuchMethod(Invocation.getter(#sortableRepository),
          returnValue: _FakeSortableRepository_20()) as _i6.SortableRepository);
  @override
  _i6.GenericRepository get genericRepository =>
      (super.noSuchMethod(Invocation.getter(#genericRepository),
          returnValue: _FakeGenericRepository_21()) as _i6.GenericRepository);
  @override
  _i10.SyncDelays get syncDelay =>
      (super.noSuchMethod(Invocation.getter(#syncDelay),
          returnValue: _FakeSyncDelays_22()) as _i10.SyncDelays);
  @override
  _i10.SyncState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeSyncState_23()) as _i10.SyncState);
  @override
  _i9.Stream<_i10.SyncState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.SyncState>.empty())
          as _i9.Stream<_i10.SyncState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i10.SyncEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i10.SyncState> mapEventToState(_i10.SyncEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i10.SyncState>.empty())
          as _i9.Stream<_i10.SyncState>);
  @override
  void onEvent(_i10.SyncEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.SyncEvent, _i10.SyncState>> transformEvents(
          _i9.Stream<_i10.SyncEvent>? events,
          _i20.TransitionFunction<_i10.SyncEvent, _i10.SyncState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue: Stream<
                  _i20.Transition<_i10.SyncEvent, _i10.SyncState>>.empty())
          as _i9.Stream<_i20.Transition<_i10.SyncEvent, _i10.SyncState>>);
  @override
  void emit(_i10.SyncState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i20.Transition<_i10.SyncEvent, _i10.SyncState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.SyncEvent, _i10.SyncState>>
      transformTransitions(
              _i9.Stream<_i20.Transition<_i10.SyncEvent, _i10.SyncState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue: Stream<
                      _i20.Transition<_i10.SyncEvent, _i10.SyncState>>.empty())
              as _i9.Stream<_i20.Transition<_i10.SyncEvent, _i10.SyncState>>);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.StreamSubscription<_i10.SyncState> listen(
          void Function(_i10.SyncState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_15<_i10.SyncState>())
          as _i9.StreamSubscription<_i10.SyncState>);
  @override
  void onChange(_i20.Change<_i10.SyncState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [PushBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushBloc extends _i2.Mock implements _i10.PushBloc {
  MockPushBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i10.PushState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakePushState_24()) as _i10.PushState);
  @override
  _i9.Stream<_i10.PushState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.PushState>.empty())
          as _i9.Stream<_i10.PushState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i9.Stream<_i10.PushState> mapEventToState(_i10.PushEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i10.PushState>.empty())
          as _i9.Stream<_i10.PushState>);
  @override
  void add(_i10.PushEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i10.PushEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.PushEvent, _i10.PushState>> transformEvents(
          _i9.Stream<_i10.PushEvent>? events,
          _i20.TransitionFunction<_i10.PushEvent, _i10.PushState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue: Stream<
                  _i20.Transition<_i10.PushEvent, _i10.PushState>>.empty())
          as _i9.Stream<_i20.Transition<_i10.PushEvent, _i10.PushState>>);
  @override
  void emit(_i10.PushState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i20.Transition<_i10.PushEvent, _i10.PushState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.PushEvent, _i10.PushState>>
      transformTransitions(
              _i9.Stream<_i20.Transition<_i10.PushEvent, _i10.PushState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue: Stream<
                      _i20.Transition<_i10.PushEvent, _i10.PushState>>.empty())
              as _i9.Stream<_i20.Transition<_i10.PushEvent, _i10.PushState>>);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.StreamSubscription<_i10.PushState> listen(
          void Function(_i10.PushState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_15<_i10.PushState>())
          as _i9.StreamSubscription<_i10.PushState>);
  @override
  void onChange(_i20.Change<_i10.PushState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GenericBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenericBloc extends _i2.Mock implements _i10.GenericBloc {
  MockGenericBloc() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i6.GenericRepository get genericRepository =>
      (super.noSuchMethod(Invocation.getter(#genericRepository),
          returnValue: _FakeGenericRepository_21()) as _i6.GenericRepository);
  @override
  _i9.StreamSubscription<dynamic> get pushSubscription =>
      (super.noSuchMethod(Invocation.getter(#pushSubscription),
              returnValue: _FakeStreamSubscription_15<dynamic>())
          as _i9.StreamSubscription<dynamic>);
  @override
  set pushSubscription(_i9.StreamSubscription<dynamic>? _pushSubscription) =>
      super.noSuchMethod(
          Invocation.setter(#pushSubscription, _pushSubscription),
          returnValueForMissingStub: null);
  @override
  _i10.SyncBloc get syncBloc =>
      (super.noSuchMethod(Invocation.getter(#syncBloc),
          returnValue: _FakeSyncBloc_16()) as _i10.SyncBloc);
  @override
  _i10.GenericState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _FakeGenericState_25()) as _i10.GenericState);
  @override
  _i9.Stream<_i10.GenericState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i10.GenericState>.empty())
          as _i9.Stream<_i10.GenericState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  _i9.Stream<_i10.GenericState> mapEventToState(_i10.GenericEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i10.GenericState>.empty())
          as _i9.Stream<_i10.GenericState>);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void add(_i10.GenericEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i10.GenericEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.GenericEvent, _i10.GenericState>> transformEvents(
          _i9.Stream<_i10.GenericEvent>? events,
          _i20.TransitionFunction<_i10.GenericEvent, _i10.GenericState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue: Stream<
                  _i20.Transition<_i10.GenericEvent, _i10.GenericState>>.empty())
          as _i9.Stream<_i20.Transition<_i10.GenericEvent, _i10.GenericState>>);
  @override
  void emit(_i10.GenericState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i20.Transition<_i10.GenericEvent, _i10.GenericState>? transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Stream<_i20.Transition<_i10.GenericEvent, _i10.GenericState>>
      transformTransitions(
              _i9.Stream<_i20.Transition<_i10.GenericEvent, _i10.GenericState>>?
                  transitions) =>
          (super.noSuchMethod(
                  Invocation.method(#transformTransitions, [transitions]),
                  returnValue: Stream<
                      _i20.Transition<_i10.GenericEvent, _i10.GenericState>>.empty())
              as _i9
                  .Stream<_i20.Transition<_i10.GenericEvent, _i10.GenericState>>);
  @override
  _i9.StreamSubscription<_i10.GenericState> listen(
          void Function(_i10.GenericState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription_15<_i10.GenericState>())
          as _i9.StreamSubscription<_i10.GenericState>);
  @override
  void onChange(_i20.Change<_i10.GenericState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ScrollController].
///
/// See the documentation for Mockito's code generation for more information.
class MockScrollController extends _i2.Mock implements _i12.ScrollController {
  MockScrollController() {
    _i2.throwOnMissingStub(this);
  }

  @override
  bool get keepScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#keepScrollOffset),
          returnValue: false) as bool);
  @override
  double get initialScrollOffset =>
      (super.noSuchMethod(Invocation.getter(#initialScrollOffset),
          returnValue: 0.0) as double);
  @override
  Iterable<_i12.ScrollPosition> get positions => (super.noSuchMethod(
      Invocation.getter(#positions),
      returnValue: <_i12.ScrollPosition>[]) as Iterable<_i12.ScrollPosition>);
  @override
  bool get hasClients =>
      (super.noSuchMethod(Invocation.getter(#hasClients), returnValue: false)
          as bool);
  @override
  _i12.ScrollPosition get position =>
      (super.noSuchMethod(Invocation.getter(#position),
          returnValue: _FakeScrollPosition_26()) as _i12.ScrollPosition);
  @override
  double get offset =>
      (super.noSuchMethod(Invocation.getter(#offset), returnValue: 0.0)
          as double);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i9.Future<void> animateTo(double? offset,
          {Duration? duration, _i12.Curve? curve}) =>
      (super.noSuchMethod(
          Invocation.method(
              #animateTo, [offset], {#duration: duration, #curve: curve}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void jumpTo(double? value) =>
      super.noSuchMethod(Invocation.method(#jumpTo, [value]),
          returnValueForMissingStub: null);
  @override
  void attach(_i12.ScrollPosition? position) =>
      super.noSuchMethod(Invocation.method(#attach, [position]),
          returnValueForMissingStub: null);
  @override
  void detach(_i12.ScrollPosition? position) =>
      super.noSuchMethod(Invocation.method(#detach, [position]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i12.ScrollPosition createScrollPosition(_i12.ScrollPhysics? physics,
          _i12.ScrollContext? context, _i12.ScrollPosition? oldPosition) =>
      (super.noSuchMethod(
          Invocation.method(
              #createScrollPosition, [physics, context, oldPosition]),
          returnValue: _FakeScrollPosition_26()) as _i12.ScrollPosition);
  @override
  String toString() => super.toString();
  @override
  void debugFillDescription(List<String>? description) => super.noSuchMethod(
      Invocation.method(#debugFillDescription, [description]),
      returnValueForMissingStub: null);
  @override
  void addListener(_i21.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i21.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [MultipartRequestBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultipartRequestBuilder extends _i2.Mock
    implements _i6.MultipartRequestBuilder {
  MockMultipartRequestBuilder() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.MultipartRequest generateFileMultipartRequest(
          {Uri? uri, _i22.Uint8List? bytes, String? authToken, String? sha1}) =>
      (super.noSuchMethod(
          Invocation.method(#generateFileMultipartRequest, [],
              {#uri: uri, #bytes: bytes, #authToken: authToken, #sha1: sha1}),
          returnValue: _FakeMultipartRequest_27()) as _i5.MultipartRequest);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MultipartRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultipartRequest extends _i2.Mock implements _i5.MultipartRequest {
  MockMultipartRequest() {
    _i2.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get fields =>
      (super.noSuchMethod(Invocation.getter(#fields),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  List<_i5.MultipartFile> get files =>
      (super.noSuchMethod(Invocation.getter(#files),
          returnValue: <_i5.MultipartFile>[]) as List<_i5.MultipartFile>);
  @override
  int get contentLength =>
      (super.noSuchMethod(Invocation.getter(#contentLength), returnValue: 0)
          as int);
  @override
  set contentLength(int? value) =>
      super.noSuchMethod(Invocation.setter(#contentLength, value),
          returnValueForMissingStub: null);
  @override
  String get method =>
      (super.noSuchMethod(Invocation.getter(#method), returnValue: '')
          as String);
  @override
  Uri get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: _FakeUri_28())
          as Uri);
  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(Invocation.getter(#headers),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  bool get persistentConnection =>
      (super.noSuchMethod(Invocation.getter(#persistentConnection),
          returnValue: false) as bool);
  @override
  set persistentConnection(bool? value) =>
      super.noSuchMethod(Invocation.setter(#persistentConnection, value),
          returnValueForMissingStub: null);
  @override
  bool get followRedirects => (super
          .noSuchMethod(Invocation.getter(#followRedirects), returnValue: false)
      as bool);
  @override
  set followRedirects(bool? value) =>
      super.noSuchMethod(Invocation.setter(#followRedirects, value),
          returnValueForMissingStub: null);
  @override
  int get maxRedirects =>
      (super.noSuchMethod(Invocation.getter(#maxRedirects), returnValue: 0)
          as int);
  @override
  set maxRedirects(int? value) =>
      super.noSuchMethod(Invocation.setter(#maxRedirects, value),
          returnValueForMissingStub: null);
  @override
  bool get finalized =>
      (super.noSuchMethod(Invocation.getter(#finalized), returnValue: false)
          as bool);
  @override
  _i5.ByteStream finalize() =>
      (super.noSuchMethod(Invocation.method(#finalize, []),
          returnValue: _FakeByteStream_29()) as _i5.ByteStream);
  @override
  _i9.Future<_i5.StreamedResponse> send() => (super.noSuchMethod(
          Invocation.method(#send, []),
          returnValue:
              Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_30()))
      as _i9.Future<_i5.StreamedResponse>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i2.Mock implements _i3.Database {
  MockDatabase() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  bool get isOpen =>
      (super.noSuchMethod(Invocation.getter(#isOpen), returnValue: false)
          as bool);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<T> transaction<T>(_i9.Future<T> Function(_i3.Transaction)? action,
          {bool? exclusive}) =>
      (super.noSuchMethod(
          Invocation.method(#transaction, [action], {#exclusive: exclusive}),
          returnValue: Future<T>.value(null)) as _i9.Future<T>);
  @override
  _i9.Future<int> getVersion() =>
      (super.noSuchMethod(Invocation.method(#getVersion, []),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<void> setVersion(int? version) =>
      (super.noSuchMethod(Invocation.method(#setVersion, [version]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<T> devInvokeMethod<T>(String? method, [dynamic arguments]) =>
      (super.noSuchMethod(
          Invocation.method(#devInvokeMethod, [method, arguments]),
          returnValue: Future<T>.value(null)) as _i9.Future<T>);
  @override
  _i9.Future<T> devInvokeSqlMethod<T>(String? method, String? sql,
          [List<Object?>? arguments]) =>
      (super.noSuchMethod(
          Invocation.method(#devInvokeSqlMethod, [method, sql, arguments]),
          returnValue: Future<T>.value(null)) as _i9.Future<T>);
  @override
  String toString() => super.toString();
  @override
  _i9.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(Invocation.method(#execute, [sql, arguments]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  _i9.Future<int> rawInsert(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(Invocation.method(#rawInsert, [sql, arguments]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> insert(String? table, Map<String, Object?>? values,
          {String? nullColumnHack, _i3.ConflictAlgorithm? conflictAlgorithm}) =>
      (super.noSuchMethod(
          Invocation.method(#insert, [
            table,
            values
          ], {
            #nullColumnHack: nullColumnHack,
            #conflictAlgorithm: conflictAlgorithm
          }),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<List<Map<String, Object?>>> query(String? table,
          {bool? distinct,
          List<String>? columns,
          String? where,
          List<Object?>? whereArgs,
          String? groupBy,
          String? having,
          String? orderBy,
          int? limit,
          int? offset}) =>
      (super.noSuchMethod(
              Invocation.method(#query, [
                table
              ], {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset
              }),
              returnValue: Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[]))
          as _i9.Future<List<Map<String, Object?>>>);
  @override
  _i9.Future<List<Map<String, Object?>>> rawQuery(String? sql,
          [List<Object?>? arguments]) =>
      (super.noSuchMethod(Invocation.method(#rawQuery, [sql, arguments]),
              returnValue: Future<List<Map<String, Object?>>>.value(
                  <Map<String, Object?>>[]))
          as _i9.Future<List<Map<String, Object?>>>);
  @override
  _i9.Future<int> rawUpdate(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(Invocation.method(#rawUpdate, [sql, arguments]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> update(String? table, Map<String, Object?>? values,
          {String? where,
          List<Object?>? whereArgs,
          _i3.ConflictAlgorithm? conflictAlgorithm}) =>
      (super.noSuchMethod(
          Invocation.method(#update, [
            table,
            values
          ], {
            #where: where,
            #whereArgs: whereArgs,
            #conflictAlgorithm: conflictAlgorithm
          }),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> rawDelete(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(Invocation.method(#rawDelete, [sql, arguments]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> delete(String? table,
          {String? where, List<Object?>? whereArgs}) =>
      (super.noSuchMethod(
          Invocation.method(
              #delete, [table], {#where: where, #whereArgs: whereArgs}),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i3.Batch batch() => (super.noSuchMethod(Invocation.method(#batch, []),
      returnValue: _FakeBatch_31()) as _i3.Batch);
}

/// A class which mocks [BaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseClient extends _i2.Mock implements _i5.BaseClient {
  MockBaseClient() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<_i5.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<_i5.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<_i5.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<_i5.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_32()))
          as _i9.Future<_i5.Response>);
  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i22.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i22.Uint8List>.value(_i22.Uint8List(0)))
          as _i9.Future<_i22.Uint8List>);
  @override
  _i9.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
          returnValue: Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_30())) as _i9.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SettingsDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsDb extends _i2.Mock implements _i3.SettingsDb {
  MockSettingsDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i13.SharedPreferences get preferences =>
      (super.noSuchMethod(Invocation.getter(#preferences),
          returnValue: _FakeSharedPreferences_33()) as _i13.SharedPreferences);
  @override
  String get language =>
      (super.noSuchMethod(Invocation.getter(#language), returnValue: '')
          as String);
  @override
  bool get alwaysUse24HourFormat =>
      (super.noSuchMethod(Invocation.getter(#alwaysUse24HourFormat),
          returnValue: false) as bool);
  @override
  bool get textToSpeech =>
      (super.noSuchMethod(Invocation.getter(#textToSpeech), returnValue: false)
          as bool);
  @override
  bool get rightCategoryExpanded =>
      (super.noSuchMethod(Invocation.getter(#rightCategoryExpanded),
          returnValue: false) as bool);
  @override
  bool get leftCategoryExpanded =>
      (super.noSuchMethod(Invocation.getter(#leftCategoryExpanded),
          returnValue: false) as bool);
  @override
  _i9.Future<dynamic> setLanguage(String? language) =>
      (super.noSuchMethod(Invocation.method(#setLanguage, [language]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> setAlwaysUse24HourFormat(bool? alwaysUse24HourFormat) =>
      (super.noSuchMethod(
          Invocation.method(#setAlwaysUse24HourFormat, [alwaysUse24HourFormat]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> setTextToSpeech(bool? textToSpeech) =>
      (super.noSuchMethod(Invocation.method(#setTextToSpeech, [textToSpeech]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> setRightCategoryExpanded(bool? expanded) => (super
      .noSuchMethod(Invocation.method(#setRightCategoryExpanded, [expanded]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> setLeftCategoryExpanded(bool? expanded) => (super
      .noSuchMethod(Invocation.method(#setLeftCategoryExpanded, [expanded]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ActivityDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityDb extends _i2.Mock implements _i3.ActivityDb {
  MockActivityDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(Invocation.getter(#tableName), returnValue: '')
          as String);
  @override
  _i3.DbMapTo<_i1.Activity> get convertToDataModel =>
      (super.noSuchMethod(Invocation.getter(#convertToDataModel),
          returnValue: (Map<String, dynamic> map) =>
              _FakeDbModel_2<_i1.Activity>()) as _i3.DbMapTo<_i1.Activity>);
  @override
  _i4.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_1())
          as _i4.Logger);
  @override
  _i3.Database get db => (super.noSuchMethod(Invocation.getter(#db),
      returnValue: _FakeDatabase_34()) as _i3.Database);
  @override
  String get GET_ALL_DIRTY =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_DIRTY), returnValue: '')
          as String);
  @override
  String get GET_BY_ID_SQL =>
      (super.noSuchMethod(Invocation.getter(#GET_BY_ID_SQL), returnValue: '')
          as String);
  @override
  String get GET_ALL_SQL_NON_DELETED =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_SQL_NON_DELETED),
          returnValue: '') as String);
  @override
  String get GET_ALL_SQL =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_SQL), returnValue: '')
          as String);
  @override
  String get MAX_REVISION_SQL =>
      (super.noSuchMethod(Invocation.getter(#MAX_REVISION_SQL), returnValue: '')
          as String);
  @override
  _i9.Future<dynamic> insert(Iterable<_i1.DbModel<_i1.Activity>>? dataModels) =>
      (super.noSuchMethod(Invocation.method(#insert, [dataModels]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<Iterable<_i1.DbModel<_i1.Activity>>> getAllDirty() =>
      (super.noSuchMethod(Invocation.method(#getAllDirty, []),
              returnValue: Future<Iterable<_i1.DbModel<_i1.Activity>>>.value(
                  <_i1.DbModel<_i1.Activity>>[]))
          as _i9.Future<Iterable<_i1.DbModel<_i1.Activity>>>);
  @override
  _i9.Future<_i1.DbModel<_i1.Activity>?> getById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getById, [id]),
              returnValue: Future<_i1.DbModel<_i1.Activity>?>.value())
          as _i9.Future<_i1.DbModel<_i1.Activity>?>);
  @override
  _i9.Future<Iterable<_i1.Activity>> getAll() => (super.noSuchMethod(
          Invocation.method(#getAll, []),
          returnValue: Future<Iterable<_i1.Activity>>.value(<_i1.Activity>[]))
      as _i9.Future<Iterable<_i1.Activity>>);
  @override
  _i9.Future<Iterable<_i1.Activity>> getAllNonDeleted() => (super.noSuchMethod(
          Invocation.method(#getAllNonDeleted, []),
          returnValue: Future<Iterable<_i1.Activity>>.value(<_i1.Activity>[]))
      as _i9.Future<Iterable<_i1.Activity>>);
  @override
  _i9.Future<int> getLastRevision() =>
      (super.noSuchMethod(Invocation.method(#getLastRevision, []),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<bool> insertAndAddDirty(Iterable<_i1.Activity>? data) =>
      (super.noSuchMethod(Invocation.method(#insertAndAddDirty, [data]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserFileDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFileDb extends _i2.Mock implements _i3.UserFileDb {
  MockUserFileDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(Invocation.getter(#tableName), returnValue: '')
          as String);
  @override
  String get GET_ALL_WITH_MISSING_FILES =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_WITH_MISSING_FILES),
          returnValue: '') as String);
  @override
  String get GET_ALL_WITH_LOADED_FILES =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_WITH_LOADED_FILES),
          returnValue: '') as String);
  @override
  String get SET_FILE_LOADED =>
      (super.noSuchMethod(Invocation.getter(#SET_FILE_LOADED), returnValue: '')
          as String);
  @override
  _i3.DbMapTo<_i1.UserFile> get convertToDataModel =>
      (super.noSuchMethod(Invocation.getter(#convertToDataModel),
          returnValue: (Map<String, dynamic> map) =>
              _FakeDbModel_2<_i1.UserFile>()) as _i3.DbMapTo<_i1.UserFile>);
  @override
  _i4.Logger get log =>
      (super.noSuchMethod(Invocation.getter(#log), returnValue: _FakeLogger_1())
          as _i4.Logger);
  @override
  _i3.Database get db => (super.noSuchMethod(Invocation.getter(#db),
      returnValue: _FakeDatabase_34()) as _i3.Database);
  @override
  String get GET_ALL_DIRTY =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_DIRTY), returnValue: '')
          as String);
  @override
  String get GET_BY_ID_SQL =>
      (super.noSuchMethod(Invocation.getter(#GET_BY_ID_SQL), returnValue: '')
          as String);
  @override
  String get GET_ALL_SQL_NON_DELETED =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_SQL_NON_DELETED),
          returnValue: '') as String);
  @override
  String get GET_ALL_SQL =>
      (super.noSuchMethod(Invocation.getter(#GET_ALL_SQL), returnValue: '')
          as String);
  @override
  String get MAX_REVISION_SQL =>
      (super.noSuchMethod(Invocation.getter(#MAX_REVISION_SQL), returnValue: '')
          as String);
  @override
  String missingFilesWithLimit(int? limit) =>
      (super.noSuchMethod(Invocation.method(#missingFilesWithLimit, [limit]),
          returnValue: '') as String);
  @override
  _i9.Future<Iterable<_i1.UserFile>> getMissingFiles({int? limit}) => (super
      .noSuchMethod(Invocation.method(#getMissingFiles, [], {#limit: limit}),
          returnValue:
              Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[])) as _i9
      .Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<Iterable<_i1.UserFile>> getAllLoadedFiles() => (super.noSuchMethod(
          Invocation.method(#getAllLoadedFiles, []),
          returnValue: Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[]))
      as _i9.Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<dynamic> setFileLoadedForId(String? id) =>
      (super.noSuchMethod(Invocation.method(#setFileLoadedForId, [id]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> insert(Iterable<_i1.DbModel<_i1.UserFile>>? dataModels) =>
      (super.noSuchMethod(Invocation.method(#insert, [dataModels]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<Iterable<_i1.DbModel<_i1.UserFile>>> getAllDirty() =>
      (super.noSuchMethod(Invocation.method(#getAllDirty, []),
              returnValue: Future<Iterable<_i1.DbModel<_i1.UserFile>>>.value(
                  <_i1.DbModel<_i1.UserFile>>[]))
          as _i9.Future<Iterable<_i1.DbModel<_i1.UserFile>>>);
  @override
  _i9.Future<_i1.DbModel<_i1.UserFile>?> getById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getById, [id]),
              returnValue: Future<_i1.DbModel<_i1.UserFile>?>.value())
          as _i9.Future<_i1.DbModel<_i1.UserFile>?>);
  @override
  _i9.Future<Iterable<_i1.UserFile>> getAll() => (super.noSuchMethod(
          Invocation.method(#getAll, []),
          returnValue: Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[]))
      as _i9.Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<Iterable<_i1.UserFile>> getAllNonDeleted() => (super.noSuchMethod(
          Invocation.method(#getAllNonDeleted, []),
          returnValue: Future<Iterable<_i1.UserFile>>.value(<_i1.UserFile>[]))
      as _i9.Future<Iterable<_i1.UserFile>>);
  @override
  _i9.Future<int> getLastRevision() =>
      (super.noSuchMethod(Invocation.method(#getLastRevision, []),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<bool> insertAndAddDirty(Iterable<_i1.UserFile>? data) =>
      (super.noSuchMethod(Invocation.method(#insertAndAddDirty, [data]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDb extends _i2.Mock implements _i3.UserDb {
  MockUserDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i13.SharedPreferences get prefs =>
      (super.noSuchMethod(Invocation.getter(#prefs),
          returnValue: _FakeSharedPreferences_33()) as _i13.SharedPreferences);
  @override
  _i9.Future<dynamic> insertUser(_i1.User? user) =>
      (super.noSuchMethod(Invocation.method(#insertUser, [user]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> deleteUser() =>
      (super.noSuchMethod(Invocation.method(#deleteUser, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TokenDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenDb extends _i2.Mock implements _i3.TokenDb {
  MockTokenDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i13.SharedPreferences get prefs =>
      (super.noSuchMethod(Invocation.getter(#prefs),
          returnValue: _FakeSharedPreferences_33()) as _i13.SharedPreferences);
  @override
  _i9.Future<dynamic> persistToken(String? token) =>
      (super.noSuchMethod(Invocation.method(#persistToken, [token]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> delete() =>
      (super.noSuchMethod(Invocation.method(#delete, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LicenseDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockLicenseDb extends _i2.Mock implements _i3.LicenseDb {
  MockLicenseDb() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i13.SharedPreferences get prefs =>
      (super.noSuchMethod(Invocation.getter(#prefs),
          returnValue: _FakeSharedPreferences_33()) as _i13.SharedPreferences);
  @override
  _i9.Future<dynamic> persistLicenses(List<_i1.License>? licenses) =>
      (super.noSuchMethod(Invocation.method(#persistLicenses, [licenses]),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  List<_i1.License> getLicenses() =>
      (super.noSuchMethod(Invocation.method(#getLicenses, []),
          returnValue: <_i1.License>[]) as List<_i1.License>);
  @override
  _i9.Future<dynamic> delete() =>
      (super.noSuchMethod(Invocation.method(#delete, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Notification].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotification extends _i2.Mock implements _i24.Notification {
  MockNotification() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i9.Future<dynamic> mockCancelAll() =>
      (super.noSuchMethod(Invocation.method(#mockCancelAll, []),
          returnValue: Future<dynamic>.value()) as _i9.Future<dynamic>);
  @override
  String toString() => super.toString();
}
