name: handi
description: Flutter app for Handi
version: 6.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  seagull_lints:
    path: ../packages/seagull_lints

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/handi_logo.png'

flutter:
  uses-material-design: true
