name: handi
description: Flutter app for Handi
version: 6.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auth:
    path: ../packages/auth
  calendar:
    path: ../packages/calendar
  equatable: ^2.0.3
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  logger: any
  package_info_plus: ^3.0.3
  repository_base:
    path: ../packages/repository/repository_base
  rxdart: ^0.27.1
  seagull_analytics:
    path: ../packages/seagull_analytics
  seagull_clock:
    path: ../packages/seagull_clock
  shared_preferences: ^2.0.8
  sqflite: ^2.2.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  http: ^0.13.5
  mocktail: ^0.3.0
  seagull_fakes:
    path: ../packages/seagull_fakes
  seagull_lints:
    path: ../packages/seagull_lints

flutter_icons:
  android: true
  image_path_android: 'assets/handi_logo_android.png'
  ios: true
  image_path_ios: 'assets/handi_logo_ios.png'


flutter:
  uses-material-design: true
