name: handi
description: Flutter app for Handi
version: 6.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  abilia_sync:
    path: ../packages/abilia_sync
  auth:
    path: ../packages/auth
  calendar:
    path: ../packages/calendar
  calendar_events:
    path: ../packages/calendar_events
  equatable: ^2.0.3
  file_storage:
    path: ../packages/file_storage
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.0.4
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^2.0.1
  flutter_local_notifications: ^15.1.0
  flutter_localizations:
    sdk: flutter
  generics:
    path: ../packages/generics
  get_it: ^7.2.0
  intl: ^0.18.0
  logging: ^1.1.0
  lokalise_flutter_sdk: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.1.0
  path_provider: ^2.0.5
  permission_handler: ^10.2.0
  repository_base:
    path: ../packages/repository/repository_base
  rxdart: ^0.27.1
  seagull_analytics:
    path: ../packages/seagull_analytics
  seagull_clock:
    path: ../packages/seagull_clock
  seagull_logging:
    path: ../packages/seagull_logging
  shared_preferences: ^2.0.8
  sortables:
    path: ../packages/sortables
  sqflite: ^2.2.5
  sqflite_common_ffi: ^2.2.5
  support_persons:
    path: ../packages/support_persons
  text_to_speech:
    path: ../packages/text_to_speech
  timezone: ^0.9.0
  ui:
    path: ../packages/ui
  user_files:
    path: ../packages/user_files
  utils:
    path: ../packages/utils

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  mocktail: ^1.0.0
  seagull_fakes:
    path: ../packages/seagull_fakes
  seagull_lints:
    path: ../packages/seagull_lints

flutter_icons:
  android: true
  image_path_android: 'assets/handi_logo_android.png'
  ios: true
  image_path_ios: 'assets/handi_logo_ios.png'


flutter:
  uses-material-design: true
