name: calendar_repository

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  logging: ^1.1.0
  repository_base:
    path: ../repository_base
  sqflite: ^2.2.0
  utils:
    path: ../../utils

dev_dependencies:
  seagull_lints:
    path: ../../seagull_lints
  test: any