name: support_persons

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc_concurrency: any
  collection: any
  equatable: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  logging: any
  repository_base:
    path: ../repository/repository_base
  shared_preferences: any
  utils:
    path: ../utils


dev_dependencies:
  seagull_lints:
    path: ../seagull_lints
