name: seagull_clock

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: any
  meta: any
  utils:
    path: ../utils

dev_dependencies:
  seagull_lints:
    path: ../seagull_lints
  test: any
