name: utils

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_timezone: any
  logging: any
  timezone: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  seagull_lints:
    path: ../seagull_lints
