name: abilia_sync

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  auth:
    path: ../auth
  bloc_test: ^9.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.5
  logging: any
  repository_base:
    path: ../repository/repository_base
  rxdart: ^0.27.1
  seagull_clock:
    path: ../seagull_clock
  shared_preferences: ^2.0.8
  sortables:
    path: ../sortables
  utils:
    path: ../utils


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  seagull_fakes:
    path: ../seagull_fakes
  seagull_lints:
    path: ../seagull_lints
