name: acapela_tts
description: Bindings to Acapela android sdk.
version: 1.2.0

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  seagull_lints:
    path: ../seagull_lints

flutter:
  plugin:
    platforms:
      android:
        package: com.abilia.acapela_tts
        pluginClass: AcapelaTtsPlugin