name: analyze

on:
  pull_request:
    branches:
      - master
      - release

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.4'
        channel: 'stable'

    - run: flutter pub get
    - run: flutter analyze .
    - run: flutter format --set-exit-if-changed .
    - run: flutter packages pub run build_runner build --delete-conflicting-outputs
    - run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: analyze
    strategy:
      matrix:
        flavor: ['mp', 'mpgo']
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.4'
        channel: 'stable'

    - run: |
        flutter test --reporter expanded --dart-define flavor=${{ matrix.flavor }} --flavor ${{ matrix.flavor }}