name: analyze

on:
  pull_request:
    branches:
      - master
      - release*
    paths-ignore:
      - '**/ios/**'
      - '**/android/**'
      - '**/*.md'

jobs:
  analyze:
    strategy:
      matrix:
        include:
          - folder: memoplanner
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./${{ matrix.folder }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        if (( $(tr -d -c '\t\n' < lib/i18n/translations.tsv | uniq -c | wc -l) > 1 )); then
          echo >&2 "translations.tsv is not uniformed in tabs"
          exit 1
        fi
    - uses: subosito/flutter-action@v2.5.0
      with:
        flutter-version: '3.0.5'
        channel: 'stable'

    - run: flutter pub get
    - run: flutter analyze .
    - run: flutter format --set-exit-if-changed .
    - run: flutter packages pub run build_runner build --delete-conflicting-outputs
    - run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: analyze
    strategy:
      matrix:
        flavor: ['mp', 'mpgo']
        include:
          - folder: memoplanner
    defaults:
      run:
        working-directory: ./${{ matrix.folder }}
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2.5.0
      with:
        flutter-version: '3.0.5'
        channel: 'stable'

    - run: |
        flutter test --reporter expanded --dart-define flavor=${{ matrix.flavor }} --flavor ${{ matrix.flavor }}
