name: CI

on:
  pull_request:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'

    - run: flutter pub get
    - run: flutter analyze .
    - run: flutter format --set-exit-if-changed .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    strategy:
      matrix:
        flavor: ['mp', 'mpgo']
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'

    - run: |
        flutter test --reporter expanded --dart-define flavor=${{ matrix.flavor }} --flavor ${{ matrix.flavor }}