name: Handi Analyze

on:
  pull_request:
    branches:
      - master
      - release*
    paths-ignore:
      - 'memoplanner/**'
      - '**/ios/**'
      - '**/android/**'
      - '**/*.md'

jobs:
  analyze:
    strategy:
      matrix:
        include:
          - folder: handi
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter format --set-exit-if-changed .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: analyze
    strategy:
      matrix:
        include:
          - folder: handi
    defaults:
      run:
        working-directory: ./${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - run: |
          flutter test --reporter expanded
