name: Handi Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'memoplanner/**'
      - 'handi/ios/**'
      - 'handi/test*/**'
      - '**/*.md'
jobs:
  analyze_and_test_packages:
    uses: ./.github/workflows/packages-analyze.yaml

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./handi
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - run: |
          flutter test --reporter github

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [test, analyze_and_test_packages]
    defaults:
      run:
        working-directory: ./handi
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - id: set_build_number
        name: Set build number
        run: |
          version=$(( $GITHUB_RUN_NUMBER + 1))
          echo "buildnumber=$version" >> $GITHUB_OUTPUT

      - name: Build artifact
        run: |
          flutter build appbundle \
            --build-number=${{ steps.set_build_number.outputs.buildnumber }} \

        env:
          KEYSTORE_PASSWORD: ${{ secrets.APPCENTER_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.APPCENTER_KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: handi/build/app/outputs/bundle/release/app-release.aab
          retention-days: 1

  upload:
    name: Upload to Google play
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    strategy:
      fail-fast: false
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-release
      - name: Upload artifact to Google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          packageName: 'com.abilia.handicalendar6'
          releaseFiles: ./app-release.aab
          track: 'internal'
          status: completed
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Clean up uploaded artifacts from GitHub storage
        uses: geekyeggo/delete-artifact@v2
        with:
          name: app-release
