name: memotrack Android Build test

on:
  push:
    branches:
      - test-**
    paths-ignore:
      - 'ios/**'
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'

    - id: set_build_number
      run: |
        version=$(( $GITHUB_RUN_NUMBER + 2000))
        echo "::set-output name=buildnumber::$version"

    - run: |
        flutter build appbundle --flavor mp --build-number=${{ steps.set_build_number.outputs.buildnumber }} --dart-define release=alpha --dart-define flavor=mp
      env:
        APPCENTER_KEYSTORE_PASSWORD: ${{ secrets.APPCENTER_KEYSTORE_PASSWORD }}
        APPCENTER_KEY_PASSWORD: ${{ secrets.APPCENTER_KEY_PASSWORD }}
    - uses: actions/upload-artifact@v3
      with:
        name: app-mp-release
        path: build/app/outputs/bundle/**/app-mp-release.aab
        retention-days: 1

  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    strategy:
      fail-fast: false
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-mp-release
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          packageName: com.abilia.memoplannergo
          releaseFiles: ./**/app-mp-release.aab
          track: memotrack
          status: completed
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Clean up uploaded artifacts from GitHub storage
        uses: geekyeggo/delete-artifact@v1
        with:
          name: app-mp-release
