name: MEMOPlanner Analyze and Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - master
      - release*
    paths:
      - 'memoplanner/**'
      - '!memoplanner/ios/**'
      - '!memoplanner/android/**'
      - 'packages/**'
      - '!packages/ui/**'
      - '!**.md'
      - '!**.yaml'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./memoplanner
    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ABILIA_OPEN_API_KEY: ${{ secrets.DEVICE_API_KEY }}
          directory: ./memoplanner/lib/env/
          file_name: .env.key
          fail_on_empty: true

      - run: |
          if (( $(tr -d -c '\t\n' < lib/i18n/translations.tsv | uniq -c | wc -l) > 1 )); then
            echo >&2 "translations.tsv is not uniformed in tabs"
            exit 1
          fi
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.2'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: git diff --exit-code
      - run: flutter analyze .
      - run: dart format --set-exit-if-changed .

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: analyze
    strategy:
      matrix:
        flavor: [ 'mp', 'mpgo' ]
    defaults:
      run:
        working-directory: ./memoplanner
    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ABILIA_OPEN_API_KEY: ${{ secrets.DEVICE_API_KEY }}
          directory: ./memoplanner/lib/env/
          file_name: .env.key
          fail_on_empty: true
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.2'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: |
          flutter test --reporter github --dart-define flavor=${{ matrix.flavor }} --flavor ${{ matrix.flavor }}
