name: Publish showcase to GitHub Pages

on:
    workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - 'showcase/**'
        - 'packages/ui/**'
        - '!**/*.md'
        - '!**/*.yaml'
jobs:
  analyze_and_test_packages:
    uses: ./.github/workflows/packages-analyze.yaml

  build:
    name: Publish showcase to github pages
    runs-on: ubuntu-latest
    needs: [analyze_and_test_packages]
    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.10.2'
          channel: 'stable'
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: showcase
          baseHref: /seagull/
